### PR TITLE
Update/readme paste callback

### PR DESCRIPTION
**Pull request by sashless**
to describe what was implemented in https://github.com/stevermeister/ngWig/pull/81

### CODE REVIEW

**Comment by sashless** [comment]
here we go @stevermeister

**Comment by stevermeister** [comment]
great job! 
but I would suggest to put this block behind installation one

**Comment by sashless** [comment]
did that @stevermeister

**Comment by stevermeister** [comment]
@sashless ,
thanks a lot for you contribution!

**Comment by sashless** [comment]
youre welcome ! But i found another typo, sorry =) https://github.com/stevermeister/ngWig/pull/88

**Pull request merged**
