### PR TITLE
Apply changes to scope when content is changed.

### PR DESCRIPTION
**Pull request by bampakoa**

### CODE REVIEW

**Comment by stevermeister** [comment]
Hi @bampakoa ,
which version of AngularJS do you use?

**Comment by bampakoa** [comment]
Hi @stevermeister.It's 1.2.16.

**Comment by bampakoa** [comment]
Hi @stevermeister.It's 1.2.16.

**Comment by stevermeister** [comment]
could you please try with Angular 1.3?

**Comment by bampakoa** [comment]
@stevermeister it works with v1.3

**Comment by stevermeister** [comment]
@bampakoa,

I've made update. Please have a look. Now it should work for both versions

**Comment by bampakoa** [comment]
@stevermeister 

I checked it and works correctly for both versions.

I also have made some improvements to a version of mine, that adds multiple headers (h1,h2,h3) and font color. Would you like to make a pull request to check it out?

**Comment by stevermeister** [comment]
>multiple headers (h1,h2,h3) and font color. Would you like to make a pull request to check it out?
yes, please, I'll have a look

**Pull request closed without merging**
