### PR TITLE
remove postinstall hook

### PR DESCRIPTION
**Pull request by sashless**
The postinstall hook is causing problems for my env 

```
Binary is fine; exiting
npm ERR! ngWig@1.1.10 postinstall: bower install && ./node_modules/.bin/grunt install
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the ngWig@1.1.10 postinstall script.
npm ERR! This is most likely a problem with the ngWig package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! bower install && ./node_modules/.bin/grunt install
npm ERR! You can get their info via:
npm ERR! npm owner ls ngWig
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.0-32-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/sashless/repos/scholar/annotation-tool
npm ERR! node -v v0.10.37
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

In addition its unnecessary when i just want to use the dist files.  Can we rename it to disable the hook ?

### CODE REVIEW

**Comment by stevermeister** [comment]
but it's part of installation, you can not just skip bower install or grunt.

it's better to look deeper what is the cause of your problem

**Comment by sashless** [comment]
The problem with `postInstall` is that it is executed after install.
That means you get files you dont want to have in case you are just jusing it as a third party lib in any application like i do.

In case you want to develop ngWig then you can run `devInstall` and get the required depdencies but without the need to that its just overhead.

**Comment by sashless** [comment]
This is because the dist files are in the repository as well. No need to build it from scratch to use it.

**Comment by sashless** [comment]
Btw, the problem for me why `postInstall` failed was that i dont have `grunt` installed.

And i will not install it anymore because i dont need it for development ;) 
But when removing/renaming the `postInstall` hook i can still load ngWig as dependency without failing on the `postInstall` and use it in any application or any environment.

Usually you split your deps into parts. 

There can be development dependencies and regular dependencies for example.

Grunt is a development dependency in that case and should be never required to run it ( what it is currently because you added it to the postInstall hook )

**Comment by stevermeister** [comment]
if you don't need dev version you can just download dist and use it, no?

**Comment by sashless** [comment]
well, nope.

Its like that:

* i have an application with a package.json
* ngWig is listed like `"ng-wig": "git+ssh://git@github.com:sashless/ngWig.git#v2.0.0",
* to start developing my application i need to install the deps using `npm install`
* this is going to install all deps 

Now i can start using ngWig because i just use the build files located in `dis`


* but after install `postInstall` hook is called in ngWig which wants to install dev depedencies which are unnecessary when ngWig is only used as dependency

**Comment by stevermeister** [comment]
why don't you want to install ngWig via bower?

`bower install ng-wig`

**Comment by sashless** [comment]
It is because I am using npm and dont want to install multiple package
manager for Frontend dependencies.

Please take a look at the Bower documentation what it says about the
postInstall hook

These hooks are not intended to provide a post-installation build step for
component authors.

https://github.com/bower/bower/blob/master/HOOKS.md

Stepan Suvorov <notifications@github.com> schrieb am Fr., 18. Sep. 2015
14:23:

**Comment by sashless** [comment]
Regardless of that it would not help to use bower because the postInstall
hook is called as well and would fails due the same reasons

Sascha Weniger <saweniger@gmail.com> schrieb am Fr., 18. Sep. 2015 14:48:

**Comment by sashless** [comment]
Ah well I think I am wrong. I doubt bower will call postInstall from package . json because there is the Bower. Rc for bower. But what is the problem to rename postInstall to devInstall to avoid problems and make it useable with npm?

**Comment by lsd** [comment]
+1 for renaming postInstall hook. It's causing me a similar problem in my application. (I don't use/need bower)

**Comment by sashless** [comment]
ping @stevermeister

**Comment by stevermeister** [comment]
@sashless 
I now want to publish correct npm package for you (here - https://www.npmjs.com/package/ng-wig)

probably we could change `package.json` to make it convenient in use for both of us.

`devInstall` - will not work automatically, right?

**Comment by sashless** [comment]
thanks @stevermeister 

yes `devInstall` will not be triggered automatically

**Comment by stevermeister** [comment]
any suggestions how to keep it being triggered automatically for my case and not triggered for yours?

**Comment by sashless** [comment]
nope sorry, i would just rename the hook to disable it.

Usually you just install the deps only once in case nothing changed so its not that much overhead for the development side but a huge benefit for the consumer side because we avoid installing unnecessary things

**Comment by sashless** [comment]
I would recommend to rename the hook and call `npm run devInstall` manually ifnecessary

**Comment by stevermeister** [comment]
created a question for it 
http://stackoverflow.com/questions/32742512/how-to-separate-dev-and-dist-script-instructions-in-package-json

**Comment by sashless** [comment]
Thanks :+1:

Stepan Suvorov <notifications@github.com> schrieb am Mi., 23. Sep. 2015
16:36:

**Comment by stevermeister** [comment]
@sashless 
ok, as far as I see there is no alternative solution for it.
Could you please add "main file" to package.json to make it complete npm package (like it was mentioned here http://stackoverflow.com/a/32749080/274500) and I'll merge you PR.

**Comment by sashless** [comment]
Would be funny If I just had answered your SO question =) awesome news! Will do that in the next days, probably on Monday!

**Comment by sashless** [comment]
i have added a `main` section @stevermeister 

But for out of the box compatibility it should try to detect the execution environment and provide appropriate exports. This should be done later at some point to ease the usability

**Comment by stevermeister** [comment]
@sashless ,

>execution environment and provide appropriate exports

I would really appreciate if you also helped me with it. To make it correct and complete npm package.

**Comment by stevermeister** [comment]
wrong button, sorry

**Comment by sashless** [comment]
Okay, I think I can work on this during the week but can't tell when I have
time

Stepan Suvorov <notifications@github.com> schrieb am Mo., 28. Sep. 2015
11:26:

**Comment by sashless** [comment]
@stevermeister i think we dont need any more code to make it compatible for any env.

The only dependency is angular and this is usually exposing a global anyway. Imo we are good to go :+1:

**Comment by stevermeister** [comment]
ok :)

**Pull request merged**
