### PR TITLE
Add dynamic binding to html - require sanitize

### PR DESCRIPTION
**Pull request by syarul**
Reset my fork, check if this work.

### CODE REVIEW

**Comment by syarul** [comment]
I already integrate this into my app, you don't have to merge it if you don't want to.

**Comment by stevermeister** [comment]
it's not about will to merge. 
I'm just trying to get the idea of such change

**Comment by syarul** [comment]
The reason behind this is simple something like Evernote where you see a snippet of your written text, you edit the text with the editor, it auto change the snippet/text on the fly, I do not have to save or have to add popup window confirmation, just by pressing return key or back button on android, the changes already happen.

**Comment by syarul** [comment]
The other reason is that I can make this without the wysiwyg editor at all using REST something like using sailsjs with mongo/redis db backend to store the data, but that's too much,  I just want simple  app where my text is store to json database into a folder using HTML5 file-writer-api, so my app can work independently without a  mongo or sailsjs.

**Pull request closed without merging**
